--- 
- name: Creates directory
  file: path={{jvm_folder}} state=directory
  sudo: yes

- name: Download Java
  command: "wget -q -O {{java_archive_path}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive_path}}"
  sudo: yes

- name: Unpack archive
  command: "tar -zxf {{java_archive_path}} -C {{jvm_folder}} creates={{java_name}}"
  sudo: yes
  
- name: Fix ownership
  file: state=directory path={{java_name}} owner=root group=root recurse=yes
  sudo: yes
  
- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'
  sudo: yes
  
- name: Clean up
  file: state=absent path={{java_archive_path}}
  sudo: yes