- hosts: jenkins
  vars:
    hostname: jenkins
    postgres_version: 9.4
    gradle_version: 2.2.1
    oracle_java_version: 8
    node_version: 0.12.0
    maven_version: 3.2.5
  remote_user: vagrant
  roles:
    - { role: base }
    - { role: oracle-java }
    - { role: gradle }
    - { role: maven }
    - { role: postgres }
    - { role: nodejs}
#    - { role: aws-cli}
#    - { role: aws-emr-cli}
#    - { role: sbt}
#    - { role: scala}
    - { role: jenkins }
