---
- name: Ensure dependencies are installed.
  apt: pkg=curl state=installed

- name: Add Jenkins apt repository key.
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    validate_certs: no
    state: present
  sudo: yes

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "deb http://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: yes
  sudo: yes

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed
  sudo: yes

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes
  sudo: yes

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    host: "{{ hostname }}"
    port: 8080
    timeout: 900

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ hostname }}:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  sudo: yes

# Update Jenkins and install configured plugins.
- include: plugins.yml
